services:
  frontend:
    build: ./images/frontend
    container_name: frontend
    ports:
      - 80:3000
    environment:
      REACT_APP_BACKEND_EXPRESS_URL: backend:4000
      REACT_APP_BACKEND_WEBSOCKET_URL: backend:4001

  backend:
    build: ./images/backend
    container_name: backend
    environment:
      MONGODB_URL: mongo
      EXPRESS_PORT: 4000
      WEBSOCKET_PORT: 4001
    ports:
      - 4000
      - 4001

  mongo:
    image: mongo
    restart: always
    container_name: mongo